project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la Visualización de Datos con Python"
  author: "Edwin John Fredy Reyes Aguirre"
  date: today
  chapters:
    - index.qmd
    - 01_Introduccion_a_seaborn.qmd
    - 02_Visualizar_dos_variables_cuantitativas.qmd
    - 03_Visualizar_variable_categorica_cuantitativa.qmd
    - 04_Personalizar_graficos_seaborn.qmd

format:
  html:
    theme: simplex
    toc: true
    toc-title: 'Contenido'
    number-sections: false
    code-copy: true
    code-overflow: wrap
    fig-align: center