project:
  type: book
  output-dir: docs

book:
  title: "Manipulación de datos con pandas"
  reader-mode: true

  author: "Edwin John Fredy Reyes Aguirre"
  date: today

  sidebar:
    style: docked
    search: true

  # En esta seccion se enlaza el repositorio de GitHub
  repo-url: https://github.com/JohnReyes02/Datacamp
  repo-subdir: Analista_de_datos_en_python\03_Manipulacion_de_datos_con_pandas
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]

  chapters:
    - index.qmd
    - part: Capítulos
      chapters:
        - 01_Transformacion_de_dataframes.qmd
        - 02_Agregar_dataframes.qmd
        - 03_Segmentar_e_indexar_dataframes.qmd
        - 04_Crear_y_visualizar_dataframes.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    code-link: false
    toc: true
    toc-title: 'Contenido'
    number-sections: false
    code-copy: true
    code-overflow: wrap
    fig-align: center



