# Introducción a Python

Descubre las maravillas de Python: por qué es popular y cómo utilizarlo. ¡No se requieren conocimientos previos!

## ¿Qué es Python?

- Python es un lenguaje de programación de propósito general utilizado para crear casi cualquier sofware.

- La sintaxis de alto nivel de Python se parece al lenguaje natural.

- Python tiene paquetes de software disponibles públicamente, que son códigos escritos por otros desarrolladores que podemos utilizar en lugar  de escribir una función desde cero.

- Es gratuito y de código abierto, lo que significa que cualquiera puede usarlo, modificarlo y distribuirlo como crea conveniente.

- Los usos más comunes de Python incluyen:
    - Automatización
    - Desarrollo Web
    - Tareas de IA
    - Informes
    - Web Scraping
    - Reconocimiento de Imagen

    
### Ejecutar tu primer script de python

En este ejercicio ejecutarás tu primer código en Python.

#### Instrucciones

- Pulsa el botón **Ejecutar código** para ejecutar el script de Python y ver los resultados en el área del shell de Python.

- Pulsa el botón **Enviar respuesta** para pasar al siguiente ejecticio.

```{python}
print('I Love Python')
```

Acabas de ejecutar tu primer código en Python. Esto es solo el comienzo; pronto estarás escribiendo programas en Python más complejos y potentes.


### Escribir tu primer script en Python

Ahora, escribirás tu primer línea de código Python.

La función `print()` de Python muestra mensajes y resultados de código en el intérprete de comandos.


#### Instrucciones 

- Utiliza la función incorporada de Python `print()` para mostrar `"Learning Python"`.


```{python}
# Replace ____ below to display "Learning Python"
print('Learning Python')
```

Haz impreso corectamente 'Learning Python', usando la función `print()` dentre del shell de Python. La función `print()` asegura que siempre mostrarás mensajes en el shell de Python.


## Sintásis de Python

- Principales operadores
    - Suma: +
    - Resta: -
    - Multiplicación *
    - División: /
    - Módulo: %

- Los comentarios en el código se escriben iniciando con un `#`

### Python como calculadora

Trabajar con números y realizar cálculos son tareas de programación muy comunes. En este ejercicio, debes realizar dos cálculos.

#### Instrucciones

- Imprime la suma de `19 + 17`.

- Imprime el resultado de restar `12` a `99`.


```{python}
# Add 19 and 17
print(19 + 17)

# Subtract 12 from 99
print(99 - 12)
```

Python puede ayudarte a hacer sumas y restas básicas, una habilidad que será útil para una variedad de tareas al construir software.


### Más cálculos

Python puede realizar cálculos más complejos, como multiplicaciones y divisiones. Ahora, realizarás estos cálculos e imprimirás sus resultados.

#### Instrucciones

- Imprime el resultado de `9` multiplicado por `2`.

- Imprime el resultado de dividir `120` enre `12`.

```{python}
# Calculate and print 9 multiplied by 2
print(9 * 2)

# Print the result of dividing 120 by 12
print(120 / 12)
```

Hasta ahora has trabajado con números y aprendido lo básico de la multiplicación y la división.¡Vamos a descubrir otros números que no son enteros en el próximo video!