project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la Estadística en Python"
  reader-mode: false

  author: "Edwin John Fredy Reyes Aguirre"
  date: today

  sidebar:
    style: docked
    search: true

  # En esta seccion se enlaza el repositorio de GitHub
  repo-url: https://github.com/JohnReyes02/Datacamp
  repo-subdir: Analista_de_datos_en_python/05_Introduccion_a_la_estadistica_en_python
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]

  chapters:
    - index.qmd
    - part: Capítulos
      chapters:
        - 01_Sintesis_estadistica.qmd
        - 02_Numeros_aleatorios_y_probabilidad.qmd
        - 03_Mas_distribuciones_y_teorema_limite_central.qmd
        - 04_Correlacion_y_diseno_de_experimentos.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true
    toc-title: 'Contenido'
    number-sections: false
    code-copy: true
    code-overflow: wrap
    fig-align: center