project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la Estadística en Python"
  author: "Edwin John Fredy Reyes Aguirre"
  date: today
  chapters:
    - index.qmd
    - 01_Sintesis_estadistica.qmd
    - 02_Numeros_aleatorios_y_probabilidad.qmd
    - 03_Mas_distribuciones_y_teorema_limite_central.qmd
    - 04_Correlacion_y_diseno_de_experimentos.qmd

format:
  html:
    theme: simplex
    toc: true
    toc-title: 'Contenido'
    number-sections: false
    code-copy: true
    code-overflow: wrap
    fig-align: center