project:
  type: book
  output-dir: docs

book:
  title: "Análisis Exploratorio de Datos en Python"
  reader-mode: false

  author: "Edwin John Fredy Reyes Aguirre"
  date: today
  chapters:
    - index.qmd
    - part: Capítulos
      chapters:
        - 01_Conocer_un_conjunto_de_datos.qmd
        - 02_Limpieza_e_imputacion_de_datos.qmd
        - 03_Relaciones_en_los_datos.qmd
        - 04_Convertir_analisis_exploratorio_en_accion.qmd

format:
  html:
    theme: 
      - cosmo
    code-link: false
    toc: true
    toc-title: 'Contenido'
    number-sections: false
    code-copy: true
    code-overflow: wrap
    fig-align: center